SET NAMES utf8mb4;

INSERT INTO `categories` (`id`, `parent_id`, `order`, `name`, `slug`, `created_at`, `updated_at`, `description`) VALUES
(1,	NULL,	1,	'Fashion',	'fashion',	NULL,	NULL,	''),
(2,	1,	1,	'Men’s Fashion',	'fashion-men-s-fashion',	NULL,	NULL,	''),
(3,	2,	1,	'Clothes',	'fashion-men-s-fashion-clothes',	NULL,	NULL,	''),
(4,	2,	1,	'Bags',	'fashion-men-s-fashion-bags',	NULL,	NULL,	''),
(5,	2,	1,	'Shoes',	'fashion-men-s-fashion-shoes',	NULL,	NULL,	''),
(6,	2,	1,	'Accessories',	'fashion-men-s-fashion-accessories',	NULL,	NULL,	''),
(7,	2,	1,	'Watches',	'fashion-men-s-fashion-watches',	NULL,	NULL,	''),
(8,	2,	1,	'Jewelry',	'fashion-men-s-fashion-jewelry',	NULL,	NULL,	''),
(9,	2,	1,	'Other',	'fashion-men-s-fashion-other',	NULL,	NULL,	''),
(10,	1,	1,	'Women’s Fashion',	'fashion-women-s-fashion',	NULL,	NULL,	''),
(11,	10,	1,	'Clothes',	'fashion-women-s-fashion-clothes',	NULL,	NULL,	''),
(12,	10,	1,	'Bags',	'fashion-women-s-fashion-bags',	NULL,	NULL,	''),
(13,	10,	1,	'Shoes',	'fashion-women-s-fashion-shoes',	NULL,	NULL,	''),
(14,	10,	1,	'Accessories',	'fashion-women-s-fashion-accessories',	NULL,	NULL,	''),
(15,	10,	1,	'Watches',	'fashion-women-s-fashion-watches',	NULL,	NULL,	''),
(16,	10,	1,	'Jewelry',	'fashion-women-s-fashion-jewelry',	NULL,	NULL,	''),
(17,	10,	1,	'Other',	'fashion-women-s-fashion-other',	NULL,	NULL,	''),
(18,	NULL,	1,	'Beauty & Skincare',	'beauty-skincare',	NULL,	NULL,	''),
(19,	18,	1,	'Men\'s',	'beauty-skincare-men-s',	NULL,	NULL,	''),
(20,	19,	1,	'Skincare',	'beauty-skincare-men-s-skincare',	NULL,	NULL,	''),
(21,	19,	1,	'Haircare',	'beauty-skincare-men-s-haircare',	NULL,	NULL,	''),
(22,	19,	1,	'Body',	'beauty-skincare-men-s-body',	NULL,	NULL,	''),
(23,	19,	1,	'Makeup',	'beauty-skincare-men-s-makeup',	NULL,	NULL,	''),
(24,	19,	1,	'Grooming',	'beauty-skincare-men-s-grooming',	NULL,	NULL,	''),
(25,	19,	1,	'Fragrances',	'beauty-skincare-men-s-fragrances',	NULL,	NULL,	''),
(26,	19,	1,	'Appliances',	'beauty-skincare-men-s-appliances',	NULL,	NULL,	''),
(27,	19,	1,	'Other',	'beauty-skincare-men-s-other',	NULL,	NULL,	''),
(28,	18,	1,	'Women\'s',	'beauty-skincare-women-s',	NULL,	NULL,	''),
(29,	28,	1,	'Skincare',	'beauty-skincare-women-s-skincare',	NULL,	NULL,	''),
(30,	28,	1,	'Haircare',	'beauty-skincare-women-s-haircare',	NULL,	NULL,	''),
(31,	28,	1,	'Body',	'beauty-skincare-women-s-body',	NULL,	NULL,	''),
(32,	28,	1,	'Makeup',	'beauty-skincare-women-s-makeup',	NULL,	NULL,	''),
(33,	28,	1,	'Grooming',	'beauty-skincare-women-s-grooming',	NULL,	NULL,	''),
(34,	28,	1,	'Fragrances',	'beauty-skincare-women-s-fragrances',	NULL,	NULL,	''),
(35,	28,	1,	'Appliances',	'beauty-skincare-women-s-appliances',	NULL,	NULL,	''),
(36,	28,	1,	'Other',	'beauty-skincare-women-s-other',	NULL,	NULL,	''),
(37,	NULL,	1,	'Electronics & Devices',	'electronics-devices',	NULL,	NULL,	''),
(38,	37,	1,	'Mobile Phone',	'electronics-devices-mobile-phone',	NULL,	NULL,	''),
(39,	37,	1,	'Tablets',	'electronics-devices-tablets',	NULL,	NULL,	''),
(40,	37,	1,	'Computers',	'electronics-devices-computers',	NULL,	NULL,	''),
(41,	37,	1,	'TV / Audio',	'electronics-devices-tv-audio',	NULL,	NULL,	''),
(42,	37,	1,	'Cameras',	'electronics-devices-cameras',	NULL,	NULL,	''),
(43,	37,	1,	'Car devices',	'electronics-devices-car-devices',	NULL,	NULL,	''),
(44,	37,	1,	'Home devices',	'electronics-devices-home-devices',	NULL,	NULL,	''),
(45,	37,	1,	'Data Storage',	'electronics-devices-data-storage',	NULL,	NULL,	''),
(46,	37,	1,	'Other',	'electronics-devices-other',	NULL,	NULL,	''),
(47,	NULL,	1,	'Electronic Accessories',	'electronic-accessories',	NULL,	NULL,	''),
(48,	47,	1,	'Mobile Phone',	'electronic-accessories-mobile-phone',	NULL,	NULL,	''),
(49,	47,	1,	'Tablets',	'electronic-accessories-tablets',	NULL,	NULL,	''),
(50,	47,	1,	'Computers',	'electronic-accessories-computers',	NULL,	NULL,	''),
(51,	47,	1,	'TV / Audio',	'electronic-accessories-tv-audio',	NULL,	NULL,	''),
(52,	47,	1,	'Cameras',	'electronic-accessories-cameras',	NULL,	NULL,	''),
(53,	47,	1,	'Car devices',	'electronic-accessories-car-devices',	NULL,	NULL,	''),
(54,	47,	1,	'Home devices',	'electronic-accessories-home-devices',	NULL,	NULL,	''),
(55,	47,	1,	'Wires and chargers',	'electronic-accessories-wires-and-chargers',	NULL,	NULL,	''),
(56,	47,	1,	'Other',	'electronic-accessories-other',	NULL,	NULL,	''),
(57,	NULL,	1,	'Sports & Outdoors',	'sports-outdoors',	NULL,	NULL,	''),
(58,	57,	1,	'Sports Apparel',	'sports-outdoors-sports-apparel',	NULL,	NULL,	''),
(59,	57,	1,	'Exercise & Fitness Equipment',	'sports-outdoors-exercise-fitness-equipment',	NULL,	NULL,	''),
(60,	57,	1,	'Outdoor Recreation',	'sports-outdoors-outdoor-recreation',	NULL,	NULL,	''),
(61,	57,	1,	'Other',	'sports-outdoors-other',	NULL,	NULL,	''),
(62,	NULL,	1,	'Kitchen',	'kitchen',	NULL,	NULL,	''),
(63,	62,	1,	'Cooking',	'kitchen-cooking',	NULL,	NULL,	''),
(64,	63,	1,	'Cookware',	'kitchen-cooking-cookware',	NULL,	NULL,	''),
(65,	63,	1,	'Appliances',	'kitchen-cooking-appliances',	NULL,	NULL,	''),
(66,	63,	1,	'Storage',	'kitchen-cooking-storage',	NULL,	NULL,	''),
(67,	63,	1,	'Other',	'kitchen-cooking-other',	NULL,	NULL,	''),
(68,	62,	1,	'Dining',	'kitchen-dining',	NULL,	NULL,	''),
(69,	68,	1,	'Utensils',	'kitchen-dining-utensils',	NULL,	NULL,	''),
(70,	68,	1,	'Plates',	'kitchen-dining-plates',	NULL,	NULL,	''),
(71,	68,	1,	'Cups',	'kitchen-dining-cups',	NULL,	NULL,	''),
(72,	68,	1,	'Bowls',	'kitchen-dining-bowls',	NULL,	NULL,	''),
(73,	68,	1,	'Other',	'kitchen-dining-other',	NULL,	NULL,	''),
(74,	62,	1,	'Other',	'kitchen-other',	NULL,	NULL,	''),
(75,	NULL,	1,	'Home & Household',	'home-household',	NULL,	NULL,	''),
(76,	75,	1,	'Decor',	'home-household-decor',	NULL,	NULL,	''),
(77,	75,	1,	'Lighting',	'home-household-lighting',	NULL,	NULL,	''),
(78,	75,	1,	'Furniture',	'home-household-furniture',	NULL,	NULL,	''),
(79,	75,	1,	'Supplies',	'home-household-supplies',	NULL,	NULL,	''),
(80,	75,	1,	'Appliances',	'home-household-appliances',	NULL,	NULL,	''),
(81,	75,	1,	'Bedding & Bath',	'home-household-bedding-bath',	NULL,	NULL,	''),
(82,	75,	1,	'Garden & Outdoor',	'home-household-garden-outdoor',	NULL,	NULL,	''),
(83,	75,	1,	'Power & Tools',	'home-household-power-tools',	NULL,	NULL,	''),
(84,	75,	1,	'Pet & Pet Supplies',	'home-household-pet-pet-supplies',	NULL,	NULL,	''),
(85,	75,	1,	'Other',	'home-household-other',	NULL,	NULL,	''),
(86,	NULL,	1,	'Food & Beverage',	'food-beverage',	NULL,	NULL,	''),
(87,	86,	1,	'Food',	'food-beverage-food',	NULL,	NULL,	''),
(88,	87,	1,	'Fresh',	'food-beverage-food-fresh',	NULL,	NULL,	''),
(89,	87,	1,	'Dried',	'food-beverage-food-dried',	NULL,	NULL,	''),
(90,	87,	1,	'Preserved',	'food-beverage-food-preserved',	NULL,	NULL,	''),
(91,	87,	1,	'Baking',	'food-beverage-food-baking',	NULL,	NULL,	''),
(92,	86,	1,	'Beverage',	'food-beverage-beverage',	NULL,	NULL,	''),
(93,	92,	1,	'Alcoholic',	'food-beverage-beverage-alcoholic',	NULL,	NULL,	''),
(94,	92,	1,	'Non-alcoholic',	'food-beverage-beverage-non-alcoholic',	NULL,	NULL,	''),
(95,	92,	1,	'Tea',	'food-beverage-beverage-tea',	NULL,	NULL,	''),
(96,	92,	1,	'Coffee',	'food-beverage-beverage-coffee',	NULL,	NULL,	''),
(97,	NULL,	1,	'Office',	'office',	NULL,	NULL,	''),
(98,	97,	1,	'Stationery',	'office-stationery',	NULL,	NULL,	''),
(99,	97,	1,	'Documents',	'office-documents',	NULL,	NULL,	''),
(100,	97,	1,	'Furniture',	'office-furniture',	NULL,	NULL,	''),
(101,	97,	1,	'Other',	'office-other',	NULL,	NULL,	''),
(102,	NULL,	1,	'Health & Wellness',	'health-wellness',	NULL,	NULL,	''),
(103,	102,	1,	'Vitamins & Supplements',	'health-wellness-vitamins-supplements',	NULL,	NULL,	''),
(104,	102,	1,	'Pharmacy',	'health-wellness-pharmacy',	NULL,	NULL,	''),
(105,	104,	1,	'First Aid',	'health-wellness-pharmacy-first-aid',	NULL,	NULL,	''),
(106,	104,	1,	'Medicine',	'health-wellness-pharmacy-medicine',	NULL,	NULL,	''),
(107,	102,	1,	'Medical Supplies & Equipment',	'health-wellness-medical-supplies-equipment',	NULL,	NULL,	''),
(108,	107,	1,	'Face Masks',	'health-wellness-medical-supplies-equipment-face-masks',	NULL,	NULL,	''),
(109,	102,	1,	'Nutrition',	'health-wellness-nutrition',	NULL,	NULL,	''),
(110,	102,	1,	'Other',	'health-wellness-other',	NULL,	NULL,	''),
(111,	NULL,	1,	'Entertainment & Hobbies',	'entertainment-hobbies',	NULL,	NULL,	''),
(112,	111,	1,	'Books',	'entertainment-hobbies-books',	NULL,	NULL,	''),
(113,	111,	1,	'Arts & Crafts',	'entertainment-hobbies-arts-crafts',	NULL,	NULL,	''),
(114,	111,	1,	'Toys & Games',	'entertainment-hobbies-toys-games',	NULL,	NULL,	''),
(115,	111,	1,	'Entertainment',	'entertainment-hobbies-entertainment',	NULL,	NULL,	''),
(116,	111,	1,	'Vintage & Collectibles',	'entertainment-hobbies-vintage-collectibles',	NULL,	NULL,	''),
(117,	111,	1,	'Other',	'entertainment-hobbies-other',	NULL,	NULL,	''),
(118,	NULL,	1,	'Travel',	'travel',	NULL,	NULL,	''),
(119,	118,	1,	'Luggage',	'travel-luggage',	NULL,	NULL,	''),
(120,	118,	1,	'Travel Essentials',	'travel-travel-essentials',	NULL,	NULL,	''),
(121,	118,	1,	'Toiletries',	'travel-toiletries',	NULL,	NULL,	''),
(122,	NULL,	1,	'Mother & Baby',	'mother-baby',	NULL,	NULL,	''),
(123,	122,	1,	'Mother',	'mother-baby-mother',	NULL,	NULL,	''),
(124,	123,	1,	'Pregnancy',	'mother-baby-mother-pregnancy',	NULL,	NULL,	''),
(125,	123,	1,	'Maternity',	'mother-baby-mother-maternity',	NULL,	NULL,	''),
(126,	122,	1,	'Baby',	'mother-baby-baby',	NULL,	NULL,	''),
(127,	126,	1,	'Clothes',	'mother-baby-baby-clothes',	NULL,	NULL,	''),
(128,	126,	1,	'Strollers, Bags & Carriers',	'mother-baby-baby-strollers-bags-carriers',	NULL,	NULL,	''),
(129,	126,	1,	'Nursing & Feeding',	'mother-baby-baby-nursing-feeding',	NULL,	NULL,	''),
(130,	126,	1,	'Cots & Cribs',	'mother-baby-baby-cots-cribs',	NULL,	NULL,	''),
(131,	126,	1,	'Toys & Walkers',	'mother-baby-baby-toys-walkers',	NULL,	NULL,	''),
(132,	126,	1,	'Others',	'mother-baby-baby-others',	NULL,	NULL,	''),
(133,	NULL,	1,	'Everything Else',	'everything-else',	NULL,	NULL,	'');
