FROM php:7.3-fpm

# Install PHP and composer dependencies
RUN apt-get update && apt-get install -qq git curl libmcrypt-dev libjpeg-dev libpng-dev libfreetype6-dev libbz2-dev zip unzip

# GD
RUN apt-get update && \
        apt-get install -y \
        libfreetype6-dev \
        libwebp-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        nano \
        libgmp-dev \
        libldap2-dev \
        netcat \
        sqlite3 \
        libsqlite3-dev && \
        docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-webp-dir=/usr/include/  --with-jpeg-dir=/usr/include/ && \
        docker-php-ext-install gd exif

# Clear out the local repository of retrieved package files
RUN apt-get clean

RUN docker-php-ext-install pdo_mysql
#RUN docker-php-ext-install zip
RUN pecl install mcrypt-1.0.2

RUN docker-php-ext-enable mcrypt

RUN pecl install xdebug-2.8.1 \
    && docker-php-ext-enable xdebug


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

